openapi: '3.0.3'
info:
  title: Neotoma ReDAR API
  version: '1.0'
servers:
  - url: http://localhost:8080
paths:
  /v0.1/doi:
    get:
      responses:
        '200':
          description: OK
    post:
      responses:
        '200':
          description: ok
  /v0.1/doi/labels:
    get:
      responses:
        '200':
          description: OK
    post:
      responses:
        '200':
          description: ok
  /v0.1/doi/embeddings:
    get:
      responses:
        '200':
          description: OK
    post:
      responses:
        '200':
          description: ok
  /v0.1/people:
    get:
      responses:
        '200':
          description: OK
    post:
      responses:
        '200':
          description: ok
  /v0.1/projects:
    get:
      responses:
        '200':
          description: OK
    post:
      responses:
        '200':
          description: ok
  /v0.1/labels:
    get:
      responses:
        '200':
          description: OK
    post:
      responses:
        '200':
          description: ok
